// utils/themeManager.js
export const getThemePreview = (themeName) => {
  const themes = {
    blue: {
      "--primary-blue": "#2563eb",
      "--primary-blue-dark": "#1d4ed8",
      "--primary-blue-light": "#dbeafe",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#0d9488",
      "--accent-teal-light": "#ccfbf1",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#f59e0b",
      "--warning-light": "#fffbeb",
      "--error": "#ef4444",
      "--error-light": "#fef2f2",
    },
    green: {
      "--primary-blue": "#059669",
      "--primary-blue-dark": "#047857",
      "--primary-blue-light": "#d1fae5",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#0d9488",
      "--accent-teal-light": "#ccfbf1",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#d97706",
      "--warning-light": "#fef3c7",
      "--error": "#dc2626",
      "--error-light": "#fef2f2",
    },
    purple: {
      "--primary-blue": "#7c3aed",
      "--primary-blue-dark": "#6d28d9",
      "--primary-blue-light": "#ede9fe",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#c026d3",
      "--accent-teal-light": "#fae8ff",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#f59e0b",
      "--warning-light": "#fffbeb",
      "--error": "#ef4444",
      "--error-light": "#fef2f2",
    },
    orange: {
      "--primary-blue": "#ea580c",
      "--primary-blue-dark": "#c2410c",
      "--primary-blue-light": "#ffedd5",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#d97706",
      "--accent-teal-light": "#fef3c7",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#ea580c",
      "--warning-light": "#fff7ed",
      "--error": "#dc2626",
      "--error-light": "#fef2f2",
    },
    rose: {
      "--primary-blue": "#e11d48",
      "--primary-blue-dark": "#be123c",
      "--primary-blue-light": "#ffe4e6",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#db2777",
      "--accent-teal-light": "#fce7f3",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#e11d48",
      "--warning-light": "#fff1f2",
      "--error": "#dc2626",
      "--error-light": "#fef2f2",
    },
    // NUEVOS TEMAS AÑADIDOS:
    indigo: {
      "--primary-blue": "#4f46e5",
      "--primary-blue-dark": "#4338ca",
      "--primary-blue-light": "#e0e7ff",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#6366f1",
      "--accent-teal-light": "#e0e7ff",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#f59e0b",
      "--warning-light": "#fffbeb",
      "--error": "#ef4444",
      "--error-light": "#fef2f2",
    },
    emerald: {
      "--primary-blue": "#10b981",
      "--primary-blue-dark": "#059669",
      "--primary-blue-light": "#d1fae5",
      "--primary-green": "#10b981",
      "--primary-green-dark": "#059669",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#14b8a6",
      "--accent-teal-light": "#ccfbf1",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#f59e0b",
      "--warning-light": "#fffbeb",
      "--error": "#ef4444",
      "--error-light": "#fef2f2",
    },
    amber: {
      "--primary-blue": "#d97706",
      "--primary-blue-dark": "#b45309",
      "--primary-blue-light": "#fef3c7",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#f59e0b",
      "--accent-teal-light": "#fef3c7",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#d97706",
      "--warning-light": "#fef3c7",
      "--error": "#dc2626",
      "--error-light": "#fef2f2",
    },
    cyan: {
      "--primary-blue": "#0891b2",
      "--primary-blue-dark": "#0e7490",
      "--primary-blue-light": "#cffafe",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#0d9488",
      "--accent-teal-light": "#ccfbf1",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#0891b2",
      "--warning-light": "#cffafe",
      "--error": "#dc2626",
      "--error-light": "#fef2f2",
    },
    fuchsia: {
      "--primary-blue": "#c026d3",
      "--primary-blue-dark": "#a21caf",
      "--primary-blue-light": "#fae8ff",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#db2777",
      "--accent-teal-light": "#fce7f3",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#c026d3",
      "--warning-light": "#fae8ff",
      "--error": "#dc2626",
      "--error-light": "#fef2f2",
    },
    slate: {
      "--primary-blue": "#475569",
      "--primary-blue-dark": "#334155",
      "--primary-blue-light": "#f1f5f9",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#64748b",
      "--accent-teal-light": "#f1f5f9",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#475569",
      "--warning-light": "#f1f5f9",
      "--error": "#dc2626",
      "--error-light": "#fef2f2",
    },
    violet: {
      "--primary-blue": "#7c3aed",
      "--primary-blue-dark": "#6d28d9",
      "--primary-blue-light": "#ede9fe",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#8b5cf6",
      "--accent-teal-light": "#ede9fe",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#7c3aed",
      "--warning-light": "#ede9fe",
      "--error": "#dc2626",
      "--error-light": "#fef2f2",
    },
    sky: {
      "--primary-blue": "#0284c7",
      "--primary-blue-dark": "#0369a1",
      "--primary-blue-light": "#e0f2fe",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#0ea5e9",
      "--accent-teal-light": "#e0f2fe",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#0284c7",
      "--warning-light": "#e0f2fe",
      "--error": "#dc2626",
      "--error-light": "#fef2f2",
    },
    lime: {
      "--primary-blue": "#65a30d",
      "--primary-blue-dark": "#4d7c0f",
      "--primary-blue-light": "#ecfccb",
      "--primary-green": "#65a30d",
      "--primary-green-dark": "#4d7c0f",
      "--primary-green-light": "#ecfccb",
      "--accent-teal": "#84cc16",
      "--accent-teal-light": "#ecfccb",
      "--success": "#65a30d",
      "--success-light": "#ecfccb",
      "--warning": "#65a30d",
      "--warning-light": "#ecfccb",
      "--error": "#dc2626",
      "--error-light": "#fef2f2",
    },
    stone: {
      "--primary-blue": "#57534e",
      "--primary-blue-dark": "#44403c",
      "--primary-blue-light": "#fafaf9",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#78716c",
      "--accent-teal-light": "#fafaf9",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#57534e",
      "--warning-light": "#fafaf9",
      "--error": "#dc2626",
      "--error-light": "#fef2f2",
    },
    pink: {
      "--primary-blue": "#db2777",
      "--primary-blue-dark": "#be185d",
      "--primary-blue-light": "#fce7f3",
      "--primary-green": "#059669",
      "--primary-green-dark": "#047857",
      "--primary-green-light": "#d1fae5",
      "--accent-teal": "#ec4899",
      "--accent-teal-light": "#fce7f3",
      "--success": "#10b981",
      "--success-light": "#ecfdf5",
      "--warning": "#db2777",
      "--warning-light": "#fce7f3",
      "--error": "#dc2626",
      "--error-light": "#fef2f2",
    },
  };

  return themes[themeName] || themes.blue;
};

export const applyTheme = (themeName) => {
  const theme = getThemePreview(themeName);
  const root = document.documentElement;

  Object.entries(theme).forEach(([property, value]) => {
    root.style.setProperty(property, value);
  });
};
